### ISSUE TITLE
pg_dump command failed

### ISSUE THREAD

**Issue by meswanb** [rap2hpoutre/pg-anonymizer#6]
@rap2hpoutre

Even though pg_dump is installed, I get this error when running pg-anonymizer:

```
npx pg-anonymizer postgres://....
npx: installed 80 in 4.721s
Launching pg_dump
pg_dump command failed. Are you sure it is installed?

root@ip-10-0-00-000:/ # pg_dump --version
pg_dump (PostgreSQL) 12.7 (Ubuntu 12.7-1.pgdg20.04+1)
```

Anything I can try?

**Comment by arnaudambro** [comment]
I thought I had the same error, but when you check the source code, the `Are you sure it is installed` is a basic error message.
If you have `pg_dump` installed, the script is not working because of another error. For instance, my error was that my connection string was wrong.

**Comment by itslenny** [comment]
@arnaudambro is there a way to see what the error is? Mine throws this error, but does not provide ANY additional details.

**Comment by imreACTmd** [comment]
I have a little time to try to redo it to do stream processing. I will let you folks know if I could figure it out, but I'm also looking for suggestions to approach this.

**Comment by imreACTmd** [comment]
All right I managed to redo the code as streams, the working code is in https://github.com/rap2hpoutre/pg-anonymizer/pull/12

**Comment by imreACTmd** [comment]
This has been resolved.

**Comment by arnaudambro** [comment]
hello @imreACTmd 
I still have the problem of @itslenny 
![image](https://user-images.githubusercontent.com/31724752/196962472-4587f162-9f7b-4357-a9b9-3d728836b0f0.png)
```
RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
    at new NodeError (node:internal/errors:371:5)
    at Socket.onChildStdout (node:child_process:459:14)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:285:11)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23) {
  code: 'ERR_CHILD_PROCESS_STDIO_MAXBUFFER',
```

I see you're talking about the `-m` flag, but I don't know how to use it ?

**Comment by arnaudambro** [comment]
alright, I tried to add `-m=5120` to the end of my command and it worked !

**Comment by imreACTmd** [comment]
just a question, if you run `npx pg-anonymizer -v` what result do you get?

**Comment by arnaudambro** [comment]
`pg-anonymizer/0.3.0 darwin-x64 node-v16.13.0`

**Comment by imreACTmd** [comment]
weird, we are at 1.0.0: 

$ npx pg-anonymizer -v
pg-anonymizer/1.0.0 darwin-x64 node-v14.18.2

**Comment by arnaudambro** [comment]
ah ! I thought that `npx` purpose was related to having the latest version...

I ran `npx pg-anonymizer@latest -v` and I have `pg-anonymizer/0.6.0 darwin-x64 node-v16.13.0`

**Comment by imreACTmd** [comment]
apparently in version 7 npx started caching downloaded packages.
